default_platform(:android)

platform :android do
  desc "Genera el APK debug"
  lane :build do
    gradle(
      task: "clean assembleDebug"
    )
    UI.success("APK generado en en: app/build/outputs/apk/debug/app-debug.apk")
  end
end